---
- name: redhat_pdns_server | downloading powerdns pre-reqs
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - yum-plugin-priorities

- name: redhat_pdns_server | downloading powerdns repo file
  get_url:
    url: "https://repo.powerdns.com/repo-files/centos-auth-40.repo"
    dest: "/etc/yum.repos.d/powerdns-auth-40.repo"

- name: redhat_pdns_server | installing powerdns
  yum:
    name: "pdns"
  notify: restart pdns
